name: Deploy Components
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'components/**/*'
      - '.github/workflows/deploy-components.workflow.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: |
          npm --prefix components i --force
      - name: Build
        run: |
          npm --prefix components run build
      - name: Release
        run: |
          npm --prefix components run semantic-release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
