name: Deploy Root
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: |
          npm i
          npm --prefix components i
      - name: Build
        run: |
          npm run build
          npm --prefix components run build
      - name: Release
        run: |
          npm run semantic-release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN_ROOT}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
